/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 03-окт-2024 12:37:24 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "OAuth_Providers" CASCADE
;

DROP TABLE IF EXISTS "Password_Resets" CASCADE
;

DROP TABLE IF EXISTS "Sessions" CASCADE
;

DROP TABLE IF EXISTS "TwoFA_Secrets" CASCADE
;

DROP TABLE IF EXISTS "Users" CASCADE
;

/* Create Tables */

CREATE TABLE "OAuth_Providers"
(
	id uuid NOT NULL,
	provider_user_id varchar NULL,
	access_token varchar(50) NULL,
	refresh_token varchar(50) NULL,
	token_expire timestamp without time zone NULL,
	provider varchar(50) NULL,
	user_id uuid NULL
)
;

CREATE TABLE "Password_Resets"
(
	id uuid NOT NULL,
	reset_token varchar(50) NULL,
	expires_at timestamp without time zone NULL,
	used boolean NULL,
	user_id uuid NULL
)
;

CREATE TABLE "Sessions"
(
	id uuid NOT NULL,
	session_token varchar(50) NULL,
	created_at timestamp without time zone NULL,
	expires_at timestamp without time zone NULL,
	user_id uuid NULL
)
;

CREATE TABLE "TwoFA_Secrets"
(
	id uuid NOT NULL,
	secret_key varchar(50) NULL,
	created_at timestamp without time zone NULL,
	last_used timestamp without time zone NULL,
	user_id uuid NULL
)
;

CREATE TABLE "Users"
(
	id uuid NOT NULL,
	email varchar(50) NOT NULL,
	password_hash varchar(50) NOT NULL,
	is_active boolean NULL,
	created_at timestamp without time zone NULL,
	update_at timestamp without time zone NULL,
	last_login timestamp without time zone NULL,
	is_2fa_enable boolean NULL,
	role varchar(50) NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "OAuth_Providers" ADD CONSTRAINT "PK_OAuth_Providers"
	PRIMARY KEY (id)
;

CREATE INDEX "IXFK_OAuth_Providers_Users" ON "OAuth_Providers" (user_id ASC)
;

ALTER TABLE "Password_Resets" ADD CONSTRAINT "PK_Password_Resets"
	PRIMARY KEY (id)
;

CREATE INDEX "IXFK_Password_Resets_Users" ON "Password_Resets" (user_id ASC)
;

ALTER TABLE "Sessions" ADD CONSTRAINT "PK_Sessions"
	PRIMARY KEY (id)
;

CREATE INDEX "IXFK_Sessions_Users" ON "Sessions" (user_id ASC)
;

ALTER TABLE "TwoFA_Secrets" ADD CONSTRAINT "PK_TwoFA_Secrets"
	PRIMARY KEY (id)
;

CREATE INDEX "IXFK_TwoFA_Secrets_Users" ON "TwoFA_Secrets" (user_id ASC)
;

ALTER TABLE "Users" ADD CONSTRAINT "PK_Users"
	PRIMARY KEY (id)
;

/* Create Foreign Key Constraints */

ALTER TABLE "OAuth_Providers" ADD CONSTRAINT "FK_OAuth_Providers_Users"
	FOREIGN KEY (user_id) REFERENCES "Users" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Password_Resets" ADD CONSTRAINT "FK_Password_Resets_Users"
	FOREIGN KEY (user_id) REFERENCES "Users" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Sessions" ADD CONSTRAINT "FK_Sessions_Users"
	FOREIGN KEY (user_id) REFERENCES "Users" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "TwoFA_Secrets" ADD CONSTRAINT "FK_TwoFA_Secrets_Users"
	FOREIGN KEY (user_id) REFERENCES "Users" (id) ON DELETE No Action ON UPDATE No Action
;
