/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 03-окт-2024 12:36:47 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "Course" CASCADE
;

DROP TABLE IF EXISTS "Course_Enrollment" CASCADE
;

DROP TABLE IF EXISTS "Lessons" CASCADE
;

DROP TABLE IF EXISTS "Lessons_File" CASCADE
;

DROP TABLE IF EXISTS "Progress" CASCADE
;

DROP TABLE IF EXISTS "Students" CASCADE
;

DROP TABLE IF EXISTS "Task_Details" CASCADE
;

DROP TABLE IF EXISTS "Task_Results" CASCADE
;

DROP TABLE IF EXISTS "Task_Tips" CASCADE
;

DROP TABLE IF EXISTS "Tasks" CASCADE
;

DROP TABLE IF EXISTS "Teachers" CASCADE
;

DROP TABLE IF EXISTS "Teachers_Courses" CASCADE
;

/* Create Tables */

CREATE TABLE "Course"
(
	id uuid NOT NULL,
	title varchar(50) NOT NULL,
	description text NULL,
	created_at timestamp without time zone NULL,
	update_at timestamp without time zone NULL,
	author_id uuid NULL,
	is_private boolean NOT NULL
)
;

CREATE TABLE "Course_Enrollment"
(
	student_id uuid NOT NULL,
	course_id uuid NOT NULL,
	enrolle_at timestamp without time zone NULL,
	complete_starus boolean NULL,
	finally_grade numeric NULL
)
;

CREATE TABLE "Lessons"
(
	id uuid NOT NULL,
	course_id uuid NOT NULL,
	title varchar(50) NULL,
	description text NULL,
	created_at timestamp without time zone NULL,
	update_at timestamp without time zone NULL,
	is_complete boolean NULL
)
;

CREATE TABLE "Lessons_File"
(
	id uuid NOT NULL,
	lesson_id uuid NOT NULL,
	type_file varchar(25) NULL,
	file_url path NOT NULL,
	file_name varchar(255) NOT NULL,
	file_size integer NULL,
	file_extention varchar(10) NOT NULL,
	upload_at timestamp without time zone NULL
)
;

CREATE TABLE "Progress"
(
	id uuid NOT NULL,
	complete_starus numeric NOT NULL,
	grade numeric NULL,
	course_id uuid NOT NULL
)
;

CREATE TABLE "Students"
(
	id uuid NOT NULL,
	user_id uuid NOT NULL,
	email varchar(50) NULL
)
;

CREATE TABLE "Task_Details"
(
	id uuid NOT NULL,
	task_id uuid NOT NULL,
	content text NULL,
	options integer NULL,
	correct_answer text NOT NULL
)
;

CREATE TABLE "Task_Results"
(
	id uuid NOT NULL,
	task_id uuid NOT NULL,
	student_id uuid NOT NULL,
	result varchar(255) NULL,
	grade numeric NULL,
	complete_at timestamp without time zone NULL
)
;

CREATE TABLE "Task_Tips"
(
	id uuid NOT NULL,
	task_id uuid NOT NULL,
	tip varchar(50) NULL,
	show_at varchar(50) NULL
)
;

CREATE TABLE "Tasks"
(
	id uuid NOT NULL,
	lesson_id uuid NULL,
	title varchar(50) NOT NULL,
	task_type char(1) NOT NULL,
	description text NULL,
	created_at timestamp without time zone NULL,
	update_at timestamp without time zone NULL
)
;

CREATE TABLE "Teachers"
(
	id uuid NOT NULL,
	user_id uuid NOT NULL,
	invite_link varchar(50) NULL
)
;

CREATE TABLE "Teachers_Courses"
(
	teacher_id uuid NOT NULL,
	course_id uuid NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Course" ADD CONSTRAINT "PK_Course"
	PRIMARY KEY (id)
;

ALTER TABLE "Course_Enrollment" ADD CONSTRAINT "PK_Course_Enrollment"
	PRIMARY KEY (student_id,course_id)
;

CREATE INDEX "IXFK_Course_Enrollment_Course" ON "Course_Enrollment" (course_id ASC)
;

CREATE INDEX "IXFK_Course_Enrollment_Students" ON "Course_Enrollment" (student_id ASC)
;

ALTER TABLE "Lessons" ADD CONSTRAINT "PK_Lessons"
	PRIMARY KEY (id)
;

CREATE INDEX "IXFK_Lessons_Course" ON "Lessons" (course_id ASC)
;

ALTER TABLE "Lessons_File" ADD CONSTRAINT "PK_Lessons_File"
	PRIMARY KEY (id)
;

CREATE INDEX "IXFK_Lessons_File_Lessons" ON "Lessons_File" (lesson_id ASC)
;

ALTER TABLE "Progress" ADD CONSTRAINT "PK_Progress"
	PRIMARY KEY (id)
;

CREATE INDEX "IXFK_Progress_Course" ON "Progress" (course_id ASC)
;

ALTER TABLE "Students" ADD CONSTRAINT "PK_Students"
	PRIMARY KEY (id)
;

ALTER TABLE "Task_Details" ADD CONSTRAINT "PK_Task_Details"
	PRIMARY KEY (id)
;

CREATE INDEX "IXFK_Task_Details_Tasks" ON "Task_Details" (task_id ASC)
;

ALTER TABLE "Task_Results" ADD CONSTRAINT "PK_Task_Results"
	PRIMARY KEY (id)
;

CREATE INDEX "IXFK_Task_Results_Tasks" ON "Task_Results" (task_id ASC)
;

ALTER TABLE "Task_Tips" ADD CONSTRAINT "PK_Task_Tips"
	PRIMARY KEY (id)
;

CREATE INDEX "IXFK_Task_Tips_Tasks" ON "Task_Tips" (task_id ASC)
;

ALTER TABLE "Tasks" ADD CONSTRAINT "PK_Tasks"
	PRIMARY KEY (id)
;

CREATE INDEX "IXFK_Tasks_Lessons" ON "Tasks" (lesson_id ASC)
;

ALTER TABLE "Teachers" ADD CONSTRAINT "PK_Teachers"
	PRIMARY KEY (id)
;

ALTER TABLE "Teachers_Courses" ADD CONSTRAINT "PK_Teachers_Courses"
	PRIMARY KEY (teacher_id,course_id)
;

CREATE INDEX "IXFK_Teachers_Courses_Course" ON "Teachers_Courses" (course_id ASC)
;

CREATE INDEX "IXFK_Teachers_Courses_Teachers" ON "Teachers_Courses" (teacher_id ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE "Course_Enrollment" ADD CONSTRAINT "FK_Course_Enrollment_Course"
	FOREIGN KEY (course_id) REFERENCES "Course" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Course_Enrollment" ADD CONSTRAINT "FK_Course_Enrollment_Students"
	FOREIGN KEY (student_id) REFERENCES "Students" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Lessons" ADD CONSTRAINT "FK_Lessons_Course"
	FOREIGN KEY (course_id) REFERENCES "Course" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Lessons_File" ADD CONSTRAINT "FK_Lessons_File_Lessons"
	FOREIGN KEY (lesson_id) REFERENCES "Lessons" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Progress" ADD CONSTRAINT "FK_Progress_Course"
	FOREIGN KEY (course_id) REFERENCES "Course" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Task_Details" ADD CONSTRAINT "FK_Task_Details_Tasks"
	FOREIGN KEY (task_id) REFERENCES "Tasks" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Task_Results" ADD CONSTRAINT "FK_Task_Results_Tasks"
	FOREIGN KEY (task_id) REFERENCES "Tasks" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Task_Tips" ADD CONSTRAINT "FK_Task_Tips_Tasks"
	FOREIGN KEY (task_id) REFERENCES "Tasks" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Tasks" ADD CONSTRAINT "FK_Tasks_Lessons"
	FOREIGN KEY (lesson_id) REFERENCES "Lessons" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Teachers_Courses" ADD CONSTRAINT "FK_Teachers_Courses_Course"
	FOREIGN KEY (course_id) REFERENCES "Course" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Teachers_Courses" ADD CONSTRAINT "FK_Teachers_Courses_Teachers"
	FOREIGN KEY (teacher_id) REFERENCES "Teachers" (id) ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE "Tasks"
	IS 'task_type_enum для task_type 
CREATE TYPE task_type_enum AS ENUM (''exercise'', ''test'', ''interactive'');'
;
