/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 03-окт-2024 12:39:58 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "Event_Enrollment" CASCADE
;

DROP TABLE IF EXISTS "Event_Reward" CASCADE
;

DROP TABLE IF EXISTS "Events" CASCADE
;

DROP TABLE IF EXISTS "Students" CASCADE
;

DROP TABLE IF EXISTS "Task_Result" CASCADE
;

DROP TABLE IF EXISTS "Tasks" CASCADE
;

/* Create Tables */

CREATE TABLE "Event_Enrollment"
(
	student_id uuid NOT NULL,
	event_id uuid NOT NULL,
	is_award boolean NULL,
	enrolled_at timestamp without time zone NULL
)
;

CREATE TABLE "Event_Reward"
(
	id uuid NOT NULL,
	student_id uuid NOT NULL,
	reward_type varchar(50) NULL,	-- enum
	reward_value numeric NULL,
	event_id uuid NULL
)
;

CREATE TABLE "Events"
(
	id uuid NOT NULL,
	reward varchar(50) NULL,
	description text NULL,
	start_at timestamp without time zone NULL,
	end_at timestamp without time zone NULL,
	is_active varchar(50) NULL,
	title varchar(50) NULL
)
;

CREATE TABLE "Students"
(
	id uuid NOT NULL,
	user_id uuid NULL
)
;

CREATE TABLE "Task_Result"
(
	id uuid NOT NULL,
	task_id uuid NOT NULL,
	student_id uuid NOT NULL,
	result varchar(255) NULL,
	score integer NULL,
	submitt_at timestamp without time zone NULL
)
;

CREATE TABLE "Tasks"
(
	id uuid NOT NULL,
	event_id uuid NOT NULL,
	task_title varchar(50) NULL,
	task_discription text NULL,
	created_at timestamp without time zone NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Event_Enrollment" ADD CONSTRAINT "PK_Event_Enrollment"
	PRIMARY KEY (student_id,event_id)
;

CREATE INDEX "IXFK_Event_Enrollment_Events" ON "Event_Enrollment" (event_id ASC)
;

CREATE INDEX "IXFK_Event_Enrollment_Students" ON "Event_Enrollment" (student_id ASC)
;

ALTER TABLE "Event_Reward" ADD CONSTRAINT "PK_Awards"
	PRIMARY KEY (id)
;

CREATE INDEX "IXFK_Awards_Students" ON "Event_Reward" (student_id ASC)
;

CREATE INDEX "IXFK_Event_Reward_Events" ON "Event_Reward" (event_id ASC)
;

ALTER TABLE "Events" ADD CONSTRAINT "PK_Events"
	PRIMARY KEY (id)
;

ALTER TABLE "Students" ADD CONSTRAINT "PK_Students"
	PRIMARY KEY (id)
;

ALTER TABLE "Task_Result" ADD CONSTRAINT "PK_Task_Result"
	PRIMARY KEY (id)
;

CREATE INDEX "IXFK_Task_Result_Students" ON "Task_Result" (student_id ASC)
;

CREATE INDEX "IXFK_Task_Result_Tasks" ON "Task_Result" (task_id ASC)
;

ALTER TABLE "Tasks" ADD CONSTRAINT "PK_Tasks"
	PRIMARY KEY (id)
;

CREATE INDEX "IXFK_Tasks_Events" ON "Tasks" (event_id ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE "Event_Enrollment" ADD CONSTRAINT "FK_Event_Enrollment_Events"
	FOREIGN KEY (event_id) REFERENCES "Events" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Event_Enrollment" ADD CONSTRAINT "FK_Event_Enrollment_Students"
	FOREIGN KEY (student_id) REFERENCES "Students" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Event_Reward" ADD CONSTRAINT "FK_Awards_Students"
	FOREIGN KEY (student_id) REFERENCES "Students" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Event_Reward" ADD CONSTRAINT "FK_Event_Reward_Events"
	FOREIGN KEY (event_id) REFERENCES "Events" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Task_Result" ADD CONSTRAINT "FK_Task_Result_Students"
	FOREIGN KEY (student_id) REFERENCES "Students" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Task_Result" ADD CONSTRAINT "FK_Task_Result_Tasks"
	FOREIGN KEY (task_id) REFERENCES "Tasks" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Tasks" ADD CONSTRAINT "FK_Tasks_Events"
	FOREIGN KEY (event_id) REFERENCES "Events" (id) ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON COLUMN "Event_Reward".reward_type
	IS 'enum'
;
