@startuml
|User|
start
:Нажимает "Предварительный просмотр курса";
|System|
:Проверяет наличие доступных материалов;
if (Материалы доступны?) then (Да)
    :Отображает материалы для просмотра;
    |User|
    :Просматривает материалы;
    :Достигает конца доступных материалов;
    |System|
    :Отображает всплывающее окно с предложением зарегистрироваться;
else (Нет)
    :Выводит сообщение "Материалы не найдены";
endif
|User|
:Закрывает окно или переходит к регистрации;
|System|
stop
@enduml
